#ifndef PROJECT_VERSION_H
#define PROJECT_VERSION_H

#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0

#define PROJECT_VERSION_STRING "1.0.0"

#endif // PROJECT_VERSION_H