CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hash_code VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    received_bytes BIGINT NOT NULL,
    sent_bytes BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ref_count INT DEFAULT 1
);
